# Generated by Django 5.1.2 on 2024-10-22 22:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hhMain', '0002_remove_post_media_post_image_post_video_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
